import type { WidgetDefinition } from '../contracts/widget-definition.js';
import { WIDGET_STATE_KINDS } from '../contracts/widget-state.js';

const COMMON_STATES = WIDGET_STATE_KINDS;

const baseCopy = {
  loading: 'Cargando información…',
  empty: 'Sin datos para mostrar en este contexto.',
  error: 'No se pudo cargar la información. Intenta de nuevo.',
  forbidden: 'Tu rol no puede ver este contenido.',
  offline: 'Modo sin conexión: mostrando datos locales o vacío.',
};

/** Seis widgets de demostración — definiciones únicamente (WIDGET-00). */
export const DEMO_WIDGET_DEFINITIONS: readonly WidgetDefinition[] = [
  {
    id: 'patient-context',
    label: 'Contexto del paciente',
    description: 'Muestra el paciente activo y el encuentro demo cuando hay contexto.',
    category: 'command-center',
    allowedRoles: ['physician', 'nurse', 'pharmacist', 'admin'],
    requiredContext: ['patient'],
    defaultSize: 'wide',
    clinicalRisk: 'low',
    dataSource: 'synthetic',
    refreshPolicy: 'on-context',
    aiMode: 'none',
    route: '/espacio/ficha',
    hiddenByDefault: false,
    requiresHumanApproval: false,
    supportedStates: COMMON_STATES,
    actions: [
      { kind: 'navigate', label: 'Abrir ficha', route: '/espacio/ficha' },
      { kind: 'command', label: 'Resumir paciente', command: 'summarize_patient' },
    ],
    copy: baseCopy,
  },
  {
    id: 'pending-drafts',
    label: 'Borradores pendientes',
    description: 'Lista borradores clínicos del usuario demo que requieren revisión.',
    category: 'clinical',
    allowedRoles: ['physician', 'nurse', 'pharmacist'],
    requiredContext: ['user'],
    defaultSize: 'medium',
    clinicalRisk: 'medium',
    dataSource: 'synthetic',
    refreshPolicy: 'on-context',
    aiMode: 'none',
    route: '/espacio/borrador/$draftId',
    hiddenByDefault: true,
    requiresHumanApproval: true,
    supportedStates: COMMON_STATES,
    actions: [{ kind: 'navigate', label: 'Revisar borrador', route: '/espacio/borrador/$draftId' }],
    copy: baseCopy,
  },
  {
    id: 'patient-summary',
    label: 'Resumen del paciente',
    description: 'Síntesis legible del contexto clínico demo.',
    category: 'patient',
    allowedRoles: ['physician', 'nurse', 'pharmacist', 'auditor'],
    requiredContext: ['patient'],
    defaultSize: 'wide',
    clinicalRisk: 'low',
    dataSource: 'synthetic',
    refreshPolicy: 'on-context',
    aiMode: 'optional-offline',
    route: '/espacio/resumen',
    command: 'summarize_patient',
    hiddenByDefault: true,
    requiresHumanApproval: false,
    supportedStates: COMMON_STATES,
    actions: [
      { kind: 'navigate', label: 'Ver resumen completo', route: '/espacio/resumen' },
      { kind: 'command', label: 'Abrir desde comando', command: 'summarize_patient' },
    ],
    copy: {
      ...baseCopy,
      aiDisclosure: 'La asistencia de IA es opcional y requiere revisión humana.',
    },
  },
  {
    id: 'active-problems',
    label: 'Problemas activos',
    description: 'Problemas clínicos activos del paciente demo.',
    category: 'clinical',
    allowedRoles: ['physician', 'nurse'],
    requiredContext: ['patient'],
    defaultSize: 'medium',
    clinicalRisk: 'medium',
    dataSource: 'synthetic',
    refreshPolicy: 'on-context',
    aiMode: 'none',
    route: '/espacio/resumen',
    hiddenByDefault: true,
    requiresHumanApproval: false,
    supportedStates: COMMON_STATES,
    actions: [{ kind: 'navigate', label: 'Ver en ficha', route: '/espacio/ficha' }],
    copy: baseCopy,
  },
  {
    id: 'recent-labs',
    label: 'Laboratorio reciente',
    description: 'Resultados de laboratorio demo de las últimas 72 horas.',
    category: 'clinical',
    allowedRoles: ['physician', 'nurse', 'pharmacist'],
    requiredContext: ['patient'],
    defaultSize: 'medium',
    clinicalRisk: 'medium',
    dataSource: 'synthetic',
    refreshPolicy: 'manual',
    aiMode: 'none',
    route: '/espacio/laboratorio',
    hiddenByDefault: true,
    requiresHumanApproval: false,
    supportedStates: COMMON_STATES,
    actions: [{ kind: 'navigate', label: 'Solicitar laboratorio', route: '/espacio/laboratorio' }],
    copy: baseCopy,
  },
  {
    id: 'my-work',
    label: 'Mi trabajo',
    description: 'Tareas asignadas al profesional demo en el tablero secundario.',
    category: 'dashboard',
    allowedRoles: ['physician', 'nurse', 'pharmacist'],
    requiredContext: ['user'],
    defaultSize: 'wide',
    clinicalRisk: 'low',
    dataSource: 'synthetic',
    refreshPolicy: 'interval',
    aiMode: 'optional-offline',
    route: '/epis2/dashboard',
    command: 'open_dashboard_work',
    hiddenByDefault: true,
    requiresHumanApproval: false,
    supportedStates: COMMON_STATES,
    actions: [
      { kind: 'navigate', label: 'Abrir tablero', route: '/epis2/dashboard' },
      { kind: 'command', label: 'Ir desde comando', command: 'open_dashboard_work' },
    ],
    copy: {
      ...baseCopy,
      aiDisclosure: 'Las sugerencias de IA no sustituyen la revisión clínica.',
    },
  },
] as const;
