/** Microcopy clínico visible — español (EPIS2-02). */
export const copy = {
  appName: 'EPIS2',
  demoBadge: 'DEMO / SINTÉTICO',
  login: {
    title: 'Iniciar sesión',
    tagline: 'Inteligencia clínica local',
    subtitle: 'Entorno de demostración — sin datos reales',
    submit: 'Entrar al Centro de Comando',
    submitting: 'Entrando…',
    usernameLabel: 'Usuario demo',
    demoKeyLabel: 'Clave demo sintética',
    demoKeyPlaceholder: 'Ej.: DEMO-CLAVE-MEDICO',
    hint: 'Claves demo públicas de laboratorio. No usar credenciales reales.',
  },
  commandCenter: {
    title: '¿Qué necesitas hacer?',
    subtitle: 'Escribe una instrucción clínica o elige una sugerencia',
    powerBarPlaceholder: 'Ej.: evoluciona al paciente, resume al paciente…',
    powerBarLabel: 'Instrucción clínica',
    aiStatusOn: 'IA local',
    aiStatusOff: 'Sin IA',
    suggestionsRoleTitle: 'Sugerencias para tu rol',
    suggestionsAiTitle: 'Con asistencia IA local',
    submit: 'Continuar',
    emptyCommand: 'Escribe qué necesitas hacer para continuar.',
    previewTitle: 'Resultado del comando',
    resolving: 'Interpretando instrucción…',
    resolvedNavigate: 'Abriendo espacio clínico…',
    needsPatient: 'Selecciona o busca un paciente antes de continuar.',
    needsClarification: 'El comando es ambiguo. Elige una opción o escribe una frase más específica.',
    clarificationTitle: 'Opciones posibles',
    forbidden: 'Tu rol no puede ejecutar este comando.',
    unknownCommand: 'No reconocimos el comando.',
    pickPatientToContinue: 'Buscar o fijar paciente',
    clinicalAlertsTitle: 'Alertas clínicas (demo)',
    clinicalAlertsHint:
      'CDS y reglas CDR en modo informativo — no bloquean comandos ni aprobación.',
    clinicalAlertsEmpty: 'Sin alertas para este paciente en el contexto actual.',
    clinicalAlertsLoading: 'Evaluando alertas…',
    alertSourceCds: 'CDS',
    alertSourceCdr: 'CDR',
    showPatientContext: 'Mostrar contexto de paciente',
    hidePatientContext: 'Ocultar contexto de paciente',
  },
  layout: {
    backToCommand: 'Volver al Centro de Comando',
    logout: 'Cerrar sesión',
  },
  dashboard: {
    title: 'Modo tablero',
    subtitle: 'Vista de trabajo — datos sintéticos demo',
    tabWork: 'Mi trabajo',
    tabPatient: 'Paciente',
    tabService: 'Servicio',
    tabNursing: 'Enfermería',
    tabPharmacy: 'Farmacia',
    tabPatientSoon: 'Tablero del paciente disponible en V1.',
    tabServiceSoon: 'Tablero del servicio disponible en V2.',
    myOpenDrafts: 'Mis borradores abiertos',
    pendingReview: 'Pendientes de revisión',
    recentPatients: 'Pacientes recientes',
    demoTasks: 'Sugerencias demo',
    emptyDrafts: 'Sin borradores abiertos.',
    emptyReview: 'Sin solicitudes de revisión.',
    emptyRecent: 'Fija un paciente desde el Centro de Comando.',
    loading: 'Cargando tablero…',
    openDraft: 'Revisar borrador',
    useCommand: 'Usar en comando',
    openBoard: 'Modo tablero',
    patientRequiresSelection:
      'Selecciona un paciente para ver su tablero. Puedes fijarlo desde la ficha o el buscador.',
    pickPatientAction: 'Elegir paciente',
    searchPatientAction: 'Buscar paciente',
    viewFullRecord: 'Ver ficha completa',
    tabServiceActive: 'Tablero del servicio (demo)',
    tabQuality: 'Calidad',
    tabQualityRestricted: 'Tablero de calidad — requiere rol auditor o administrador.',
    gridColumnTitle: 'Título',
    gridColumnPatient: 'Paciente',
    gridColumnType: 'Tipo',
    gridColumnStatus: 'Estado',
    gridColumnUpdated: 'Actualizado',
    gridColumnDemoCase: 'Caso demo',
    gridLoading: 'Cargando tabla…',
    metricOpenDrafts: 'Borradores abiertos',
    metricPendingReview: 'Pendientes de revisión',
    metricDemoTasks: 'Sugerencias demo',
  },
  schedulerSpike: {
    title: 'Spike Scheduler (MUI-10)',
    subtitle: 'Evaluación aislada — datos sintéticos, sin API de citas',
    evalBanner:
      'LIC-007 en estado EVALUATE: no usar en flujos clínicos ni menú principal hasta aprobación de producto y modelo Appointment.',
    calendarTitle: 'Event Calendar (Community, alpha v9)',
    calendarHint: 'Vista semanal con recursos demo (boxes). Solo lectura en este spike.',
    loading: 'Cargando calendario…',
    findingsTitle: 'Hallazgos del spike',
    findings: [
      '@mui/x-scheduler 9.0.0-alpha.4 (MIT Community) instalado con peer deps MUI 7+; stack EPIS2 usa MUI 6 — requiere alineación antes de producción.',
      'API alpha: posibles breaking changes hasta release estable (julio 2026 estimado por MUI).',
      'Premium aporta recurrencia, timeline denso y lazy loading — no incluido en este spike.',
      'Sin modelo API Appointment/recursos en EPIS2: alternativa Community = lista + DatePicker (LIC-007).',
    ],
  },
  ai: {
    panelTitle: 'Asistencia clínica (IA local)',
    statusOn: 'Asistencia de IA disponible',
    statusOff: 'Modo manual (sin asistencia de IA)',
    humanReviewRequired:
      'Las respuestas de IA son orientativas. Deben revisarse y, si aplica, guardarse como borrador con aprobación humana.',
    ragTitle: 'Consulta documental con fuentes',
    ragPlaceholder: 'Ej. laboratorio, epicrisis…',
    ragSubmit: 'Consultar con citas',
    citations: 'Fuentes',
    summary24h: 'Resumen 24 h (demo)',
    recentRuns: 'Ejecuciones IA recientes',
  },
  interop: {
    stagingTitle: 'Lotes en staging (solo lectura)',
    hl7Validate: 'Validar HL7 v2',
    hl7Placeholder: 'MSH|^~\\&|...',
    hl7Valid: 'Mensaje HL7 válido (demo)',
    hl7Invalid: 'HL7 con errores',
    fhirExportHint: 'Export FHIR habilitado; importación deshabilitada (SoT EPIS2).',
    schemaVersion: 'Versión de esquema',
    metricsTitle: 'Indicadores operativos',
    auditTitle: 'Auditoría reciente',
    gridColumnEvent: 'Evento',
    gridColumnUser: 'Usuario',
    gridColumnEntity: 'Entidad',
    gridColumnBatch: 'Lote',
    gridColumnSource: 'Origen',
    gridColumnRecords: 'Registros',
    gridColumnStagedAt: 'Ingreso staging',
    gridColumnAt: 'Fecha y hora',
  },
  inpatient: {
    census: 'Censo de camas',
    occupied: 'Ocupada',
    available: 'Disponible',
    criticalUnacked: 'Críticos sin acuse',
    noCriticals: 'Sin críticos pendientes en el servicio.',
    acknowledge: 'Acusar recibo',
    probableDischarge: 'Altas probables',
    pendingTeam: 'Pendientes del equipo',
    openPatient: 'Ver ficha',
    activeOrders: 'Órdenes activas del servicio',
    admitTitle: 'Ingreso hospitalario (demo)',
    admitSubmit: 'Admitir en cama',
    transferBed: 'Trasladar',
    dischargePatient: 'Alta operativa',
    prepareDischarge: 'Preparar epicrisis',
    selectBed: 'Cama disponible',
    admitSuccess: 'Ingreso registrado — requiere revisión humana.',
    transferSuccess: 'Traslado registrado.',
    dischargeSuccess: 'Alta operativa registrada.',
    scheduledMar: 'MAR programado (ventana activa)',
    noScheduledMar: 'Sin dosis en ventana horaria actual.',
    doubleCheckRequired: 'Doble chequeo requerido',
    pharmacyValidations: 'Validaciones farmacéuticas pendientes',
    reconciliation: 'Conciliación medicamentosa',
    noPharmacyPending: 'Sin validaciones pendientes.',
  },
  longitudinal: {
    title: 'Historia clínica (demo)',
    problems: 'Problemas activos',
    allergies: 'Alergias',
    medications: 'Medicación activa',
    observations: 'Observaciones recientes',
    documents: 'Documentos indexados',
    timeline: 'Línea de tiempo',
    encounters: 'Encuentros',
    emptySection: 'Sin registros en esta sección.',
    documentRef: 'Referencia demo',
    searchDocuments: 'Buscar en documentos',
    searchPlaceholder: 'Título o referencia…',
    searchNoHits: 'Sin coincidencias en documentos indexados.',
    searchSemanticHint: 'Búsqueda semántica con fuentes (demo)',
    intakeTitle: 'Cargar documento (demo)',
    intakePlaceholder: 'Texto del documento o nota clínica…',
    intakeSubmit: 'Indexar borrador',
    intakeSuccess: 'Documento indexado — requiere revisión humana.',
    exportSummary: 'Exportar resumen',
    exportSummaryPdf: 'Exportar PDF',
    gridColumnLabTest: 'Examen',
    gridColumnLabValue: 'Resultado',
    gridColumnLabDate: 'Fecha',
  },
  activePatient: {
    none: 'Sin paciente activo — fija uno para encadenar comandos y formularios.',
    pinHint: 'Elige un paciente demo para abrir su ficha y acciones clínicas.',
    change: 'Cambiar paciente',
    workspace: 'Ficha',
    workspaceSubtitle: 'Contexto longitudinal demo — datos sintéticos',
    quickActions: 'Acciones rápidas',
    approvedNotes: 'Notas aprobadas',
    pendingDrafts: 'Borradores del paciente',
    noNotes: 'Sin notas aprobadas aún.',
    noDrafts: 'Sin borradores abiertos.',
    openDraft: 'Revisar',
    searchForm: 'Buscar con formulario dedicado',
    commandPanelTitle: 'Paciente activo',
    pickPatient: 'Elegir paciente demo',
    clinicalContextTitle: 'Contexto clínico (demo)',
    summaryActiveProblems: 'Problemas activos',
    summaryRecentEvents: 'Últimas 24 h',
    summaryLabs: 'Laboratorio / estudios',
    summaryMedications: 'Medicación activa',
    summaryPending: 'Pendientes',
    summaryAlerts: 'Alertas documentadas',
  },
  drafts: {
    reviewTitle: 'Revisión de borrador',
    contentTitle: 'Contenido',
    versionsTitle: 'Historial de versiones',
    loading: 'Cargando borrador…',
    sendToReview: 'Enviar a revisión',
    sentToReview: 'Borrador enviado a revisión.',
    approveHuman: 'Aprobar (humano)',
    approvalDisclaimer:
      'La aprobación humana es obligatoria antes de registrar la nota clínica final.',
    approvedSuccess: 'Aprobación registrada. Nota clínica creada.',
    approveError: 'No se pudo aprobar. Verifica permisos y estado.',
    transitionError: 'Transición de estado no permitida.',
    openReview: 'Ir a revisión',
    backToFicha: 'Volver a la ficha',
    continueEditing: 'Continuar edición',
    previewTruncated: 'Vista previa — campos con contenido (máx. 12).',
    statusLabels: {
      draft: 'Borrador',
      editing: 'En edición',
      ready_for_review: 'Listo para revisión',
      rejected: 'Rechazado',
      cancelled: 'Cancelado',
      approved: 'Aprobado',
    },
  },
  tree: {
    loading: 'Cargando árbol…',
    empty: 'Sin nodos para mostrar.',
    navTitle: 'Navegación clínica',
    documentTypes: {
      pdf: 'PDF',
      txt: 'Texto',
      image: 'Imagen',
      referral: 'Interconsulta',
      lab_report: 'Informe de laboratorio',
      other: 'Otros',
    },
  },
  charts: {
    loading: 'Cargando gráfico…',
    labTrendTitle: 'Tendencia INR (demo)',
    vitalsTrendTitle: 'Frecuencia cardiaca (demo)',
    heartRateSeries: 'FC (lpm)',
    serviceKpiTitle: 'Indicadores del servicio',
    emptyTrend: 'Sin datos para graficar.',
  },
  forms: {
    encounterDate: 'Fecha del encuentro',
    scheduledDate: 'Fecha programada',
    needsPatient:
      'Este formulario requiere un paciente. Búscalo o elige uno desde la ficha clínica.',
    searchPatient: 'Buscar paciente',
    backToFicha: 'Volver a la ficha',
    forbidden: 'Tu rol no puede usar este formulario.',
    validationRequired: 'Revisa los campos obligatorios antes de guardar.',
    demoValidLocal:
      'Formulario válido en demo local. Conecta un paciente y la API para guardar el borrador.',
    loadPatientsError: 'No hay pacientes demo disponibles. Verifica que la API y la base estén activas.',
    saveDraftError: 'No se pudo guardar el borrador.',
    saveDraft: 'Guardar borrador',
    searchPatients: 'Cargar pacientes demo',
    suggestAi: 'Sugerir con IA (demo)',
    suggestingAi: 'Generando sugerencia…',
    aiUnavailable: 'IA no disponible. Puedes completar el formulario manualmente.',
    aiRejected: 'La sugerencia IA no fue válida. Revisa y escribe manualmente.',
    aiApplied: 'Sugerencia aplicada. Debes revisar y aprobar como humano.',
  },
  errors: {
    genericTitle: 'Algo salió mal',
    genericMessage: 'No pudimos completar la acción. Intenta de nuevo.',
    notFoundTitle: 'Página no encontrada',
    notFoundMessage: 'La ruta solicitada no existe en EPIS2.',
    sessionExpiredTitle: 'Sesión expirada',
    sessionExpiredMessage:
      'Tu sesión ya no es válida. Vuelve a iniciar sesión para continuar en el Centro de Comando.',
    sessionExpiredAction: 'Iniciar sesión',
    forbiddenTitle: 'Acceso no permitido',
    forbiddenMessage:
      'Tu rol o permisos actuales no permiten esta acción. Si crees que es un error, contacta al administrador del entorno demo.',
    forbiddenAction: 'Volver al Centro de Comando',
    retry: 'Reintentar',
  },
  roles: {
    physician: 'Médico',
    nurse: 'Enfermería',
    pharmacist: 'Farmacia',
    admin: 'Administración',
    auditor: 'Auditoría',
  },
  themePreferences: {
    title: 'Preferencias de apariencia',
    pageDescription:
      'Personaliza color, modo, densidad, contraste y movimiento. No modifica alertas ni la seguridad clínica.',
    openLink: 'Abrir preferencias de apariencia',
    backToCommand: 'Volver al Centro de Comando',
    accent: 'Tema de color',
    density: 'Densidad',
    motion: 'Movimiento',
    mode: 'Modo',
    contrast: 'Contraste',
    modeLight: 'Modo claro',
    modeDark: 'Modo oscuro',
    accentClinicalBlue: 'Azul clínico',
    accentTeal: 'Verde azulado calmado',
    accentGreen: 'Verde calmado',
    accentViolet: 'Violeta sobrio',
    accentNeutral: 'Neutro',
    densityComfortable: 'Cómoda',
    densityCompact: 'Compacta',
    motionStandard: 'Estándar',
    motionReduced: 'Reducido',
    contrastStandard: 'Estándar',
    contrastHigh: 'Alto',
    safetyNote: 'Los colores de borrador, aprobación y alertas críticas no se personalizan.',
  },
} as const;

export type DemoRole = keyof typeof copy.roles;
