/** Microcopy clínico visible — español (EPIS2-02). */
export const copy = {
  appName: 'EPIS2',
  demoBadge: 'DEMO / SINTÉTICO',
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Entorno de demostración — sin datos reales',
    submit: 'Entrar al Centro de Comando',
    submitting: 'Entrando…',
    usernameLabel: 'Usuario demo',
    demoKeyLabel: 'Clave demo sintética',
    demoKeyPlaceholder: 'Ej.: DEMO-CLAVE-MEDICO',
    hint: 'Claves demo públicas de laboratorio. No usar credenciales reales.',
  },
  commandCenter: {
    title: '¿Qué necesitas hacer?',
    subtitle: 'Escribe una instrucción clínica o elige una sugerencia',
    powerBarPlaceholder: 'Ej.: evoluciona al paciente, resume al paciente…',
    powerBarLabel: 'Instrucción clínica',
    aiStatusOn: 'IA local',
    aiStatusOff: 'Sin IA',
    suggestionsRoleTitle: 'Sugerencias para tu rol',
    suggestionsAiTitle: 'Con asistencia IA local',
    submit: 'Continuar',
    emptyCommand: 'Escribe qué necesitas hacer para continuar.',
    previewTitle: 'Resultado del comando',
    resolving: 'Interpretando instrucción…',
    resolvedNavigate: 'Abriendo espacio clínico…',
    needsPatient: 'Selecciona o busca un paciente antes de continuar.',
    needsClarification: 'El comando es ambiguo. Prueba una frase más específica.',
    forbidden: 'Tu rol no puede ejecutar este comando.',
    unknownCommand: 'No reconocimos el comando.',
    clinicalAlertsTitle: 'Alertas clínicas (demo)',
    clinicalAlertsHint:
      'CDS y reglas CDR en modo informativo — no bloquean comandos ni aprobación.',
    clinicalAlertsEmpty: 'Sin alertas para este paciente en el contexto actual.',
    clinicalAlertsLoading: 'Evaluando alertas…',
    alertSourceCds: 'CDS',
    alertSourceCdr: 'CDR',
  },
  layout: {
    backToCommand: 'Volver al Centro de Comando',
  },
  dashboard: {
    title: 'Modo tablero',
    subtitle: 'Vista de trabajo — datos sintéticos demo',
    tabWork: 'Mi trabajo',
    tabPatient: 'Paciente',
    tabService: 'Servicio',
    tabPatientSoon: 'Tablero del paciente disponible en V1.',
    tabServiceSoon: 'Tablero del servicio disponible en V2.',
    myOpenDrafts: 'Mis borradores abiertos',
    pendingReview: 'Pendientes de revisión',
    recentPatients: 'Pacientes recientes',
    demoTasks: 'Sugerencias demo',
    emptyDrafts: 'Sin borradores abiertos.',
    emptyReview: 'Sin solicitudes de revisión.',
    emptyRecent: 'Fija un paciente desde el Centro de Comando.',
    loading: 'Cargando tablero…',
    openDraft: 'Revisar borrador',
    useCommand: 'Usar en comando',
    openBoard: 'Modo tablero',
    patientRequiresSelection: 'Selecciona un paciente en el Centro de Comando para ver su tablero.',
    viewFullRecord: 'Ver ficha completa',
    tabServiceActive: 'Tablero del servicio (demo)',
    tabQuality: 'Calidad',
    tabQualityRestricted: 'Tablero de calidad — requiere rol auditor o administrador.',
    gridColumnTitle: 'Título',
    gridColumnPatient: 'Paciente',
    gridColumnType: 'Tipo',
    gridColumnStatus: 'Estado',
    gridColumnUpdated: 'Actualizado',
    gridColumnDemoCase: 'Caso demo',
    gridLoading: 'Cargando tabla…',
  },
  ai: {
    panelTitle: 'Asistencia clínica (IA local)',
    statusOn: 'Ollama disponible',
    statusOff: 'Modo manual (sin Ollama)',
    humanReviewRequired:
      'Las respuestas de IA son orientativas. Deben revisarse y, si aplica, guardarse como borrador con aprobación humana.',
    ragTitle: 'Consulta documental con fuentes',
    ragPlaceholder: 'Ej. laboratorio, epicrisis…',
    ragSubmit: 'Consultar con citas',
    citations: 'Fuentes',
    summary24h: 'Resumen 24 h (demo)',
    recentRuns: 'Ejecuciones IA recientes',
  },
  interop: {
    stagingTitle: 'Lotes en staging (solo lectura)',
    hl7Validate: 'Validar HL7 v2',
    hl7Placeholder: 'MSH|^~\\&|...',
    hl7Valid: 'Mensaje HL7 válido (demo)',
    hl7Invalid: 'HL7 con errores',
    fhirExportHint: 'Export FHIR habilitado; importación deshabilitada (SoT EPIS2).',
    schemaVersion: 'Versión de esquema',
    metricsTitle: 'Indicadores operativos',
    auditTitle: 'Auditoría reciente',
    gridColumnEvent: 'Evento',
    gridColumnUser: 'Usuario',
    gridColumnEntity: 'Entidad',
    gridColumnBatch: 'Lote',
    gridColumnSource: 'Origen',
    gridColumnRecords: 'Registros',
    gridColumnStagedAt: 'Ingreso staging',
    gridColumnAt: 'Fecha y hora',
  },
  inpatient: {
    census: 'Censo de camas',
    occupied: 'Ocupada',
    available: 'Disponible',
    criticalUnacked: 'Críticos sin acuse',
    noCriticals: 'Sin críticos pendientes en el servicio.',
    acknowledge: 'Acusar recibo',
    probableDischarge: 'Altas probables',
    pendingTeam: 'Pendientes del equipo',
    openPatient: 'Ver ficha',
    activeOrders: 'Órdenes activas del servicio',
  },
  longitudinal: {
    title: 'Historia clínica (demo)',
    problems: 'Problemas activos',
    allergies: 'Alergias',
    medications: 'Medicación activa',
    observations: 'Observaciones recientes',
    documents: 'Documentos indexados',
    timeline: 'Línea de tiempo',
    encounters: 'Encuentros',
    emptySection: 'Sin registros en esta sección.',
    documentRef: 'Referencia demo',
    searchDocuments: 'Buscar en documentos',
    searchPlaceholder: 'Título o referencia…',
    searchNoHits: 'Sin coincidencias en documentos indexados.',
    gridColumnLabTest: 'Examen',
    gridColumnLabValue: 'Resultado',
    gridColumnLabDate: 'Fecha',
  },
  activePatient: {
    none: 'Sin paciente activo — fija uno para encadenar comandos',
    pinHint: 'Elige un paciente demo para abrir su ficha y acciones clínicas.',
    change: 'Cambiar paciente',
    workspace: 'Ficha',
    workspaceSubtitle: 'Contexto longitudinal demo — datos sintéticos',
    quickActions: 'Acciones rápidas',
    approvedNotes: 'Notas aprobadas',
    pendingDrafts: 'Borradores del paciente',
    noNotes: 'Sin notas aprobadas aún.',
    noDrafts: 'Sin borradores abiertos.',
    openDraft: 'Revisar',
    searchForm: 'Buscar con formulario dedicado',
    commandPanelTitle: 'Paciente activo',
    pickPatient: 'Elegir paciente demo',
    clinicalContextTitle: 'Contexto clínico (demo)',
    summaryActiveProblems: 'Problemas activos',
    summaryRecentEvents: 'Últimas 24 h',
    summaryLabs: 'Laboratorio / estudios',
    summaryMedications: 'Medicación activa',
    summaryPending: 'Pendientes',
    summaryAlerts: 'Alertas documentadas',
  },
  drafts: {
    reviewTitle: 'Revisión de borrador',
    contentTitle: 'Contenido',
    versionsTitle: 'Historial de versiones',
    loading: 'Cargando borrador…',
    sendToReview: 'Enviar a revisión',
    sentToReview: 'Borrador enviado a revisión.',
    approveHuman: 'Aprobar (humano)',
    approvalDisclaimer:
      'La aprobación humana es obligatoria antes de registrar la nota clínica final.',
    approvedSuccess: 'Aprobación registrada. Nota clínica creada.',
    approveError: 'No se pudo aprobar. Verifica permisos y estado.',
    transitionError: 'Transición de estado no permitida.',
    openReview: 'Ir a revisión',
    statusLabels: {
      draft: 'Borrador',
      editing: 'En edición',
      ready_for_review: 'Listo para revisión',
      rejected: 'Rechazado',
      cancelled: 'Cancelado',
      approved: 'Aprobado',
    },
  },
  charts: {
    loading: 'Cargando gráfico…',
    labTrendTitle: 'Tendencia INR (demo)',
    vitalsTrendTitle: 'Frecuencia cardiaca (demo)',
    heartRateSeries: 'FC (lpm)',
    serviceKpiTitle: 'Indicadores del servicio',
    emptyTrend: 'Sin datos para graficar.',
  },
  forms: {
    encounterDate: 'Fecha del encuentro',
    scheduledDate: 'Fecha programada',
    needsPatient: 'Selecciona un paciente demo antes de continuar.',
    saveDraft: 'Guardar borrador',
    searchPatients: 'Cargar pacientes demo',
    suggestAi: 'Sugerir con IA (demo)',
    suggestingAi: 'Generando sugerencia…',
    aiUnavailable: 'IA no disponible. Puedes completar el formulario manualmente.',
    aiRejected: 'La sugerencia IA no fue válida. Revisa y escribe manualmente.',
    aiApplied: 'Sugerencia aplicada. Debes revisar y aprobar como humano.',
  },
  errors: {
    genericTitle: 'Algo salió mal',
    genericMessage: 'No pudimos completar la acción. Intenta de nuevo.',
    notFoundTitle: 'Página no encontrada',
    notFoundMessage: 'La ruta solicitada no existe en EPIS2.',
    retry: 'Reintentar',
  },
  roles: {
    physician: 'Médico',
    nurse: 'Enfermería',
    pharmacist: 'Farmacia',
    admin: 'Administración',
    auditor: 'Auditoría',
  },
} as const;

export type DemoRole = keyof typeof copy.roles;
