-- MF-155: rol aplicación sin BYPASSRLS (superuser epis2 omite RLS).

DO $do$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'epis2_app') THEN
    CREATE ROLE epis2_app WITH LOGIN PASSWORD 'epis2' NOSUPERUSER NOBYPASSRLS;
  ELSE
    ALTER ROLE epis2_app WITH LOGIN PASSWORD 'epis2' NOSUPERUSER NOBYPASSRLS;
  END IF;
END
$do$;

GRANT CONNECT ON DATABASE epis2 TO epis2_app;
GRANT USAGE ON SCHEMA public TO epis2_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO epis2_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO epis2_app;

ALTER DEFAULT PRIVILEGES FOR ROLE epis2 IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO epis2_app;
ALTER DEFAULT PRIVILEGES FOR ROLE epis2 IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO epis2_app;

UPDATE epis2_schema_meta SET version = 'epis2-app-role', applied_at = NOW() WHERE id = 1;
