import { defineBlueprint, field, section } from '../factory.js';

export const prescriptionBlueprint = defineBlueprint({
  blueprintId: 'prescription',
  label: 'Receta médica',
  purpose: 'Prescripción con revisión humana',
  intentIds: ['prepare_prescription'],
  allowedRoles: ['physician', 'pharmacist'],
  routePath: '/espacio/receta',
  outputKind: 'ORDER_DRAFT',
  requiresPatient: true,
  requiresEncounter: true,
  sections: [
    section('rx', 'Prescripción', [
      'medication',
      'dose',
      'quantity',
      'route',
      'frequency',
      'duration',
    ]),
    section('instructions', 'Indicaciones', ['patientInstructions', 'clinicalNotes']),
  ],
  fields: [
    field('medication', 'Medicamento', 'text', {
      required: true,
      columnSpan: 8,
      catalogAutocomplete: 'medication',
      variableKey: 'rx.medication',
      fhirPath: 'MedicationRequest.medicationCodeableConcept.text',
      auditLevel: 'clinical',
      aiAllowed: true,
      printMapping: { chartMode: 'paper', sectionId: 'orders', slot: 'medication' },
      searchable: true,
    }),
    field('dose', 'Dosis', 'text', {
      required: true,
      columnSpan: 4,
      variableKey: 'rx.dose',
      fhirPath: 'MedicationRequest.dosageInstruction[0].doseAndRate[0].doseQuantity.value',
      auditLevel: 'clinical',
      aiAllowed: true,
    }),
    field('quantity', 'Cantidad', 'text', {
      required: true,
      columnSpan: 4,
      variableKey: 'rx.quantity',
      fhirPath: 'MedicationRequest.dispenseRequest.quantity.value',
      auditLevel: 'clinical',
      aiAllowed: false,
    }),
    field('route', 'Vía', 'select', {
      options: ['oral', 'intravenosa', 'topica'],
      columnSpan: 4,
      variableKey: 'rx.route',
      fhirPath: 'MedicationRequest.dosageInstruction[0].route.text',
      auditLevel: 'clinical',
      aiAllowed: true,
    }),
    field('frequency', 'Frecuencia', 'text', {
      required: true,
      columnSpan: 4,
      variableKey: 'rx.frequency',
      fhirPath: 'MedicationRequest.dosageInstruction[0].timing.code.text',
      auditLevel: 'clinical',
      aiAllowed: true,
    }),
    field('duration', 'Duración del tratamiento', 'text', {
      required: true,
      columnSpan: 4,
      variableKey: 'rx.duration',
      fhirPath: 'MedicationRequest.dosageInstruction[0].timing.repeat.boundsDuration',
      auditLevel: 'clinical',
      aiAllowed: false,
    }),
    field('patientInstructions', 'Indicaciones al paciente', 'textarea', {
      required: true,
      variableKey: 'rx.patient_instructions',
      fhirPath: 'MedicationRequest.dosageInstruction[0].patientInstruction',
      auditLevel: 'legal',
      aiAllowed: true,
      printMapping: { chartMode: 'paper', sectionId: 'orders', slot: 'instructions' },
    }),
    field('clinicalNotes', 'Notas clínicas (internas)', 'textarea', {
      variableKey: 'rx.clinical_notes',
      auditLevel: 'clinical',
      aiAllowed: true,
    }),
  ],
  validations: [
    { fieldId: 'medication', message: 'Medicamento requerido' },
    { fieldId: 'dose', message: 'Dosis requerida' },
    { fieldId: 'quantity', message: 'Cantidad requerida' },
    { fieldId: 'frequency', message: 'Frecuencia requerida' },
    { fieldId: 'duration', message: 'Duración requerida' },
    { fieldId: 'patientInstructions', message: 'Indicaciones al paciente requeridas' },
  ],
});
