import type { EpisRadScreenAudit } from './radDiscipline.js';

/**
 * Inventario auditado — base para modo diseño y migración incremental.
 * migration: done | partial | pending
 */
export const EPIS_RAD_SCREEN_REGISTRY: readonly EpisRadScreenAudit[] = [
  {
    id: 'command',
    route: '/comando',
    surface: 'command',
    primaryTask: 'Decidir intención clínica',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: false,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'search',
    mode: 'command-center',
    iconBudget: 6,
    actionBudget: 0,
    scrollPolicy: 'single',
  },
  {
    id: 'patient-chart',
    route: '/espacio/ficha',
    surface: 'workspace',
    primaryTask: 'Revisar contexto del paciente',
    scaffold: 'EpisClinicalWorkspaceShell',
    actionBar: 'none',
    preferGridOverCards: false,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'split-workspace',
    iconBudget: 12,
    scrollPolicy: 'embedded',
    notes: 'Ola 3 UX-B.2 — antecedentes/documentos/actividad compactos + split historial IDC 21–29',
  },
  {
    id: 'patient-chart-classic',
    route: '/espacio/ficha?mode=classic',
    surface: 'workspace',
    primaryTask: 'Ficha paciente modo clásico EMR',
    scaffold: 'EpisClassicMd3Shell',
    actionBar: 'none',
    preferGridOverCards: false,
    keyboardNav: true,
    migration: 'partial',
    migrationStatus: 'partial',
    md3Pattern: 'supporting-pane',
    mode: 'classic',
    iconBudget: 10,
    actionBudget: 1,
    scrollPolicy: 'main-pane-only',
    notes: 'MF-CLASSIC-EMR-MD3 — vista alternativa sin reemplazar /comando',
  },
  {
    id: 'clinical-form-evolution-classic',
    route: '/espacio/evolucion?mode=classic',
    surface: 'form',
    primaryTask: 'Evolución modo clásico EMR',
    scaffold: 'EpisClassicMd3Shell',
    actionBar: 'single',
    preferGridOverCards: false,
    keyboardNav: true,
    migration: 'partial',
    migrationStatus: 'partial',
    md3Pattern: 'supporting-pane',
    mode: 'classic',
    iconBudget: 10,
    actionBudget: 1,
    scrollPolicy: 'main-pane-only',
    notes: 'MF-CLASSIC-EMR-MD3 — formulario en main pane, contexto en supporting pane',
  },
  {
    id: 'dashboard-classic-view',
    route: '/epis2/dashboard?view=classic',
    surface: 'workspace',
    primaryTask: 'Dashboard administrativo vista clásica',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'partial',
    migrationStatus: 'partial',
    md3Pattern: 'supporting-pane',
    mode: 'classic',
    iconBudget: 8,
    actionBudget: 0,
    scrollPolicy: 'embedded',
    notes: 'MF-CLASSIC-EMR-MD3 — enlace admin desde nav clásica',
  },
  {
    id: 'patient-search',
    route: '/espacio/buscar-paciente',
    surface: 'grid',
    primaryTask: 'Buscar y seleccionar paciente',
    scaffold: 'EpisRadScreenShell',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'data-grid + PatientSearchAutocomplete',
    scrollPolicy: 'embedded',
    notes: 'Fase B — autocomplete L5 + grid demo',
  },
  {
    id: 'clinical-form-evolution',
    route: '/espacio/evolucion',
    surface: 'form',
    primaryTask: 'Registrar evolución (borrador)',
    scaffold: 'EpisRadScreenShell',
    actionBar: 'single',
    preferGridOverCards: false,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisClinicalTwoPaneLayout + form-accordion',
    actionBudget: 1,
    scrollPolicy: 'section',
    notes: 'Fase B — scrollspy contexto + collapseNonPrimarySections',
  },
  {
    id: 'draft-review',
    route: '/espacio/borrador/:id',
    surface: 'document',
    primaryTask: 'Revisar y aprobar borrador',
    scaffold: 'EpisRadScreenShell',
    actionBar: 'single',
    preferGridOverCards: false,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisRadDocumentSurface + approval ActionBar',
    actionBudget: 1,
    notes: 'Fase B — revisión borrador con ActionBar única RAD',
  },
  {
    id: 'dashboard-md3',
    route: '/epis2/dashboard?mode=dashboard',
    surface: 'grid',
    primaryTask: 'Sala de control operacional',
    scaffold: 'EpisDashboardMd3Shell',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'partial',
    migrationStatus: 'partial',
    md3Pattern: 'list-detail',
    mode: 'dashboard',
    iconBudget: 8,
    actionBudget: 0,
    scrollPolicy: 'main-grid-only',
    notes: 'MF-DASHBOARD-MD3 — tercer modo canónico; no reemplaza /comando',
  },
  {
    id: 'three-modes-orchestration',
    route: '/comando',
    surface: 'command',
    primaryTask: 'Orquestación Command ↔ Classic ↔ Dashboard',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: false,
    keyboardNav: true,
    migration: 'partial',
    migrationStatus: 'partial',
    md3Pattern: 'mode-switcher',
    mode: 'command-center',
    iconBudget: 6,
    actionBudget: 0,
    scrollPolicy: 'single',
    notes: 'MF-THREE-MODES-ORCHESTRATION — árbol canónico en apps/web/src/modes/; home /comando',
  },
  {
    id: 'dashboard-work',
    route: '/epis2/dashboard?tab=work&mode=dashboard',
    surface: 'grid',
    primaryTask: 'Listar pendientes de trabajo',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisRadDashboardTabShell + WorklistDraftGrid',
    scrollPolicy: 'embedded',
    notes: 'Bulk actions en borradores',
  },
  {
    id: 'dashboard-patient',
    route: '/epis2/dashboard?tab=patient',
    surface: 'grid',
    primaryTask: 'Resumen paciente activo',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisRadDashboardTabShell + problems/timeline grids',
    scrollPolicy: 'embedded',
    notes: 'MF-RAD-M3-A + L5 ClinicalDataGrid vía DashboardHomogeneousGrid',
  },
  {
    id: 'dashboard-service',
    route: '/epis2/dashboard?tab=service',
    surface: 'grid',
    primaryTask: 'Censo y flujo hospitalización',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisRadDashboardTabShell + census grid',
    scrollPolicy: 'embedded',
    notes: 'Acciones por fila movidas a bulk/contexto',
  },
  {
    id: 'dashboard-nursing',
    route: '/epis2/dashboard?tab=nursing',
    surface: 'grid',
    primaryTask: 'MAR y borradores enfermería',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'MAR grid + bulk',
    scrollPolicy: 'embedded',
  },
  {
    id: 'clinical-form-procedure',
    route: '/espacio/procedimiento',
    surface: 'form',
    primaryTask: 'Solicitar procedimiento (borrador)',
    scaffold: 'EpisRadScreenShell',
    actionBar: 'single',
    preferGridOverCards: false,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisClinicalFormPage + RHF',
    actionBudget: 1,
    scrollPolicy: 'section',
    notes: 'Fase B-04 — IDC 57 procedure_request',
  },
  {
    id: 'dashboard-pharmacy',
    route: '/epis2/dashboard?tab=pharmacy',
    surface: 'grid',
    primaryTask: 'Cola farmacéutica',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisRadDashboardTabShell + validations/dispensing grids + accordion',
    scrollPolicy: 'embedded',
    notes: 'Fase B-04 — colas farmacia en grids RAD + Y-Site IDC 161',
  },
  {
    id: 'dashboard-emergency',
    route: '/epis2/dashboard?tab=emergency',
    surface: 'grid',
    primaryTask: 'Triaje urgencia',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'triage grid',
    scrollPolicy: 'embedded',
  },
  {
    id: 'dashboard-icu',
    route: '/epis2/dashboard?tab=icu',
    surface: 'grid',
    primaryTask: 'Mapa camas UCI',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisRadDashboardTabShell + bed grid + monitoring accordion',
    scrollPolicy: 'embedded',
    notes: 'Bulk handover/epicrisis en mapa camas; monitoreo colapsado',
  },
  {
    id: 'dashboard-quality',
    route: '/epis2/dashboard?tab=quality',
    surface: 'grid',
    primaryTask: 'Calidad e interoperabilidad',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisRadDashboardTabShell + panel grids + acordeones IAAS/calidad',
    scrollPolicy: 'embedded',
    notes: 'Interop staging/audit unificados en DashboardPanelGridSection',
  },
  {
    id: 'dashboard-specialty',
    route: '/epis2/dashboard?tab=specialty',
    surface: 'grid',
    primaryTask: 'Paneles especialidad',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisRadDashboardTabShell + partogram/oncology grids + accordion',
    scrollPolicy: 'embedded',
    notes: 'Paneles gráficos secundarios en acordeón',
  },
  {
    id: 'results-inbox',
    route: '/espacio/resultados',
    surface: 'grid',
    primaryTask: 'Revisar resultados pendientes',
    scaffold: 'EpisRadScreenShell',
    actionBar: 'none',
    preferGridOverCards: true,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'EpisRadGridSurface + critical/pending grids',
    scrollPolicy: 'embedded',
    notes: 'MF-RAD-M3-A — migrado desde listas',
  },
  {
    id: 'login',
    route: '/login',
    surface: 'form',
    primaryTask: 'Autenticarse',
    scaffold: 'EpisAppScaffold',
    actionBar: 'none',
    preferGridOverCards: false,
    keyboardNav: true,
    migration: 'done',
    migrationStatus: 'done',
    md3Pattern: 'simple-form',
  },
];

export function auditForPath(pathname: string): EpisRadScreenAudit | undefined {
  const normalized = pathname.split('?')[0] ?? pathname;
  return EPIS_RAD_SCREEN_REGISTRY.find((entry) => {
    const routeBase = entry.route.split('?')[0] ?? entry.route;
    if (routeBase.includes(':')) {
      const prefix = routeBase.split(':')[0] ?? routeBase;
      return normalized.startsWith(prefix);
    }
    return normalized === routeBase || normalized.startsWith(`${routeBase}/`);
  });
}

export function auditForLocation(pathname: string, search = ''): EpisRadScreenAudit | undefined {
  const withSearch = search ? `${pathname}?${search.replace(/^\?/, '')}` : pathname;
  const exact = EPIS_RAD_SCREEN_REGISTRY.find((e) => e.route === withSearch);
  if (exact) return exact;
  return auditForPath(pathname);
}
